package hu.raven.puppet.configuration

enum class AlgorithmParameters {
    ITERATION_LIMIT,
    SIZE_OF_POPULATION,
    VEHICLE_COUNT,

    MUTATION_PERCENTAGE,
    CLONE_COUNT,
    CLONE_SEGMENT_LENGTH,
    CLONE_CYCLE_COUNT,

    GENE_TRANSFER_SEGMENT_LENGTH,
    INJECTION_COUNT,

    OPTIMISATION_STEP_LIMIT,
}