/**
 * DRP
 * This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.raven.puppet.model.task

import hu.raven.puppet.model.physics.Gramm
import hu.raven.puppet.model.physics.Second
import hu.raven.puppet.model.physics.Stere

data class CostGraphVertex(
    val location: Gps = Gps(),
    val time: Second = Second(0L),
    val volume: Stere = Stere(0L),
    val weight: Gramm = Gramm(0L)
)

