/**
 * DRP
 * This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.raven.puppet.model.task

data class CostGraph(
    val center: Gps = Gps(),
    val objectives: Array<CostGraphVertex> = arrayOf(),
    val edgesBetween: Array<Array<CostGraphEdge>> = arrayOf(),
    val edgesFromCenter: Array<CostGraphEdge> = arrayOf(),
    val edgesToCenter: Array<CostGraphEdge> = arrayOf()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CostGraph

        if (center != other.center) return false
        if (!objectives.contentEquals(other.objectives)) return false
        if (!edgesBetween.contentEquals(other.edgesBetween)) return false
        if (!edgesFromCenter.contentEquals(other.edgesFromCenter)) return false
        if (!edgesToCenter.contentEquals(other.edgesToCenter)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = center.hashCode()
        result = 31 * result + objectives.contentHashCode()
        result = 31 * result + edgesBetween.contentHashCode()
        result = 31 * result + edgesFromCenter.contentHashCode()
        result = 31 * result + edgesToCenter.contentHashCode()
        return result
    }
}