/**
 * DRP
 * This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.raven.puppet.model.task

data class Task(
    val transportUnits: Array<TransportUnit> = arrayOf(),
    val costGraph: CostGraph = CostGraph()
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Task

        if (!transportUnits.contentEquals(other.transportUnits)) return false
        if (costGraph != other.costGraph) return false

        return true
    }

    override fun hashCode(): Int {
        var result = transportUnits.contentHashCode()
        result = 31 * result + costGraph.hashCode()
        return result
    }
}

