/**
 * DRP
 * This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.raven.puppet.model.task

import hu.raven.puppet.model.physics.*

data class TransportUnit(
    val workTimePerDay: Second = Second(0),
    val volumeCapacity: Stere = Stere(0),
    val weightCapacity: Gramm = Gramm(0),
    val vehicleSpeed: MeterPerSecond = MeterPerSecond(0),
    val salary: EuroPerSecond = EuroPerSecond(0),
    val fuelConsumption: LiterPerMeter = LiterPerMeter(0),
    val fuelPrice: EuroPerLiter = EuroPerLiter(0),
    val basePrice: Euro = Euro(0)
)

