/**
* DRP
* This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.raven.puppet.model.mtsp

import java.util.*

data class DGps(
    var id: String = UUID.randomUUID().toString(),
    var orderInOwner: Int = 0,
    val latitude: Float = 0.0f,
    val longitude: Float = 0.0f
) {

}

