/**
 * DRP
 * This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akos.hollo-szabo@qlndc.hu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package hu.raven.puppet.model.mtsp

import java.util.*

data class DSalesman(
    var id: String = UUID.randomUUID().toString(),
    val name: String = "",
    var orderInOwner: Int = 0,
    val workTime_SecondPerDay: Long = 0L,

    val volumeCapacity_Stere: Long = 0L,
    val weightCapacity_Gramm: Long = 0L,

    val vechicleSpeed_MeterPerSecond: Long = 0L,

    val payment_EuroPerSecond: Double = 0.0,

    val fuelConsuption_LiterPerMeter: Double = 0.0,
    val fuelPrice_EuroPerLiter: Double = 0.0,

    val basePrice_Euro: Double = 0.0
)

