/**
* DRP
* This is the hu.bme.hu.raven.puppet.utility.main server of QLM's DRP system
*
* OpenAPI spec version: 1.0.0
* Contact: akos.hollo-szabo@qlndc.hu
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.raven.puppet.model.mtsp

import java.math.BigDecimal
import java.util.*

data class DSetting (
    var id: String = UUID.randomUUID().toString(),
    val name: String="",
    val iterLimit: BigDecimal= BigDecimal(0),
    val timeLimit_Second: BigDecimal=BigDecimal(0),
    val algorithm: String=""
)

